apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controlplane
  labels:
    {{- include "condux.labels" . | nindent 4 }}
    app.kubernetes.io/component: controlplane
spec:
  selector:
    {{- include "condux.selectorLabels" (dict "Release" .Release "component" "controlplane") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.controlplane.port }}
      targetPort: {{ .Values.controlplane.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-relay
  labels:
    {{- include "condux.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
spec:
  selector:
    {{- include "condux.selectorLabels" (dict "Release" .Release "component" "relay") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.relay.port }}
      targetPort: {{ .Values.relay.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "condux.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "condux.selectorLabels" (dict "Release" .Release "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
